import type { Domain } from '@/lib/supabase/types';

// Short taglines for table display (5-6 words max)
export const DOMAIN_TAGLINES: Record<string, string> = {
    tech: 'Websites, apps, and digital tools',
    finance: 'Budgets, tracking, and money',
    sni: 'Stage setup, sound, and lights',
    disco: 'Security, discipline, crowd control',
    logistics: 'Equipment, transport, venue setup',
    prc: 'Press, media, and campaigning',
    inhouse: 'Campus events and competitions',
    sponsorship: 'Brands, pitches, and deals',
    operations: 'Scheduling, coordination, registrations',
    media: 'Film, photo, and content',
    design: 'Posters, merch, visual identity',
    hospitality: 'Guests, food, and comfort',
    cultural: 'Dance, music, drama events',
    fyi: 'Internal comms and coordination',
};

export const DOMAINS_DATA: Omit<Domain, 'id'>[] = [
    {
        name: 'Sponsorship',
        slug: 'sponsorship',
        venue: 'BE Block - 111',
        description: 'Bring in the brands. Pitch, negotiate, and seal deals that fund the fest.',
        what_they_do: 'Identify potential sponsors, create pitch decks, negotiate partnerships, and maintain sponsor relationships.',
        whatsapp_link: null,
        icon: 'S',
    },
    {
        name: 'Logistics',
        slug: 'logistics',
        venue: 'BE Block - G12',
        description: 'Move mountains (and stage equipment). The unsung heroes of every event.',
        what_they_do: 'Handle venue setup, equipment management, transportation, supply chains, and on-ground coordination.',
        whatsapp_link: null,
        icon: 'L',
    },
    {
        name: 'Tech',
        slug: 'tech',
        venue: 'BE Block - G09',
        description: 'Build the digital backbone of AT\'26. From websites to apps, make things happen.',
        what_they_do: 'Develop and maintain event websites, apps, internal tools, QR systems, and digital infrastructure that powers the fest.',
        whatsapp_link: null,
        icon: 'T',
    },
    {
        name: 'Finance',
        slug: 'finance',
        venue: 'BE Block - G09',
        description: 'Handle the money that makes the magic happen. Budget, track, optimize.',
        what_they_do: 'Manage event budgets, process transactions, handle reimbursements, track expenses, and ensure financial accountability.',
        whatsapp_link: null,
        icon: 'F',
    },
    {
        name: 'Inhouse',
        slug: 'inhouse',
        venue: 'BE Block - G02',
        description: 'Light up the campus with events and competitions. Create unforgettable experiences.',
        what_they_do: 'Plan and execute in-house events, competitions, workshops, and gaming tournaments as part of the fest schedule.',
        whatsapp_link: null,
        icon: 'I',
    },
    {
        name: 'SNI',
        slug: 'sni',
        venue: 'BE Block - G06 & G07',
        description: 'Build and manage the stage infrastructure for all AT\'26 events.',
        what_they_do: 'Stage setup, sound systems, lighting rigs, infra budgets, venue prep, and making sure every event has a solid physical foundation.',
        whatsapp_link: null,
        icon: 'S',
    },
    {
        name: 'PRC',
        slug: 'prc',
        venue: 'BE Block - G04',
        description: 'Craft the narrative. Be the voice of AT\'26 to sponsors, media, and the world.',
        what_they_do: 'Write press releases, manage media relations, coordinate with sponsors, and handle all external communications and campaigning.',
        whatsapp_link: null,
        icon: 'P',
    },
    {
        name: 'Media',
        slug: 'media',
        venue: 'BE Block - Studio-1 - 9th floor',
        description: 'Capture the magic. Film, photograph, and produce content that lives forever.',
        what_they_do: 'Photography, videography, live streaming, after-movies, reels, and all visual media production for the fest.',
        whatsapp_link: null,
        icon: 'M',
    },
    {
        name: 'Cultural',
        slug: 'cultural',
        venue: 'BE Block - 112',
        description: 'Curate the soul of AT\'26. Dance, music, drama — bring culture to life.',
        what_they_do: 'Plan and manage cultural performances, coordinate with artists, organize music/dance/drama events and competitions.',
        whatsapp_link: null,
        icon: 'C',
    },
    {
        name: 'Design',
        slug: 'design',
        venue: 'BE Block - 112',
        description: 'Make AT\'26 look fire. Posters, merch, stage design — all you.',
        what_they_do: 'Create posters, social media graphics, merchandise designs, stage backdrops, and the overall visual identity.',
        whatsapp_link: null,
        icon: 'D',
    },
    {
        name: 'DISCO',
        slug: 'disco',
        venue: 'MRD Block',
        description: 'Keep the vibes safe and orderly. Be the backbone of event security.',
        what_they_do: 'Ensure crowd management, enforce venue rules, coordinate with security, and maintain discipline during events.',
        whatsapp_link: null,
        icon: 'D',
    },
    {
        name: 'Operations',
        slug: 'operations',
        venue: 'BE Block - G11 (ground floor)',
        description: 'Run the show behind the scenes. Coordinate everything that makes AT\'26 tick.',
        what_they_do: 'Coordinate between departments, manage schedules, handle registrations, and ensure seamless event operations.',
        whatsapp_link: null,
        icon: 'O',
    },
    {
        name: 'Hospitality',
        slug: 'hospitality',
        venue: 'BE Block - G08',
        description: 'Welcome guests like royalty. Food, comfort, and warm smiles.',
        what_they_do: 'Manage guest relations, food & beverages, accommodation for visiting artists, and ensure hospitality standards.',
        whatsapp_link: null,
        icon: 'H',
    },
    {
        name: 'FYI',
        slug: 'fyi',
        venue: 'BE Block - 108',
        description: 'The glue that holds everyone together. Internal coordination and knowledge base.',
        what_they_do: 'Internal communications, documentation, announcements, knowledge management, and cross-team coordination.',
        whatsapp_link: null,
        icon: 'F',
    },
];
